### ISSUE TITLE
GsonUnitTestMixin should be considered only for tests

### ISSUE THREAD

**Issue by jljouannic** [robfletcher/grails-gson#33]
Because this plugin embeds a `GsonUnitTestMixin` class which inherits from `GsonUnitTestMixin`, makes it dependant to `grails-test`, `grails-plugin-testing` and `spring-test` artifacts. This is particularly a problem if someone (me) wants to use this plugin in a mavenized grails project.

If I simply add a dependency to this plugin in the `pom.xml` file, executing a `mvn test` leads to a compilation error on `GsonUnitTestMixin.groovy` because `GsonUnitTestMixin` class cannot be resolved.

I tried to change the scope of both `grails-plugin-testing` and `grails-test` library from `test` to `provided`. This helped to build the project, but it brought unwanted (but quite expected) side effects at runtime. After a request to the application, the code which serialize an object to JSON using `GSON` throws the following:

```
java.lang.ClassNotFoundException: org.springframework.mock.web.MockHttpServletRequest
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2436)
    at java.lang.Class.getDeclaredMethods(Class.java:1793)
    at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
    at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
    at grails.plugin.gson.converters.GSON.render(GSON.groovy:57)
    at grails.plugin.gson.api.ArtefactEnhancer$_enhanceControllers_closure1.doCall(ArtefactEnhancer.groovy:29)
    ...
```

I wonder if their is a way to only consider the `GsonUnitTestMixin` class just for tests.

**Comment by robfletcher** [comment]
That's interesting. I've never used Grails with maven so I wasn't aware of the implications of including test artifacts in the plugin. If the plugin depended on a binary jar file that contained the test support classes would you be able to exclude it from your maven build?

**Comment by jljouannic** [comment]
> If the plugin depended on a binary jar file that contained the test support classes would you be able to exclude it from your maven build?

Don't you mean the opposite? The test support class depends on the others, not the contrary. But yes, I think that would work. With this solution I would be able to simply add a `compile` dependency to the gson plugin to make everything work. And if I wanted to write some tests about serialization, I could then add a `test` dependency to the binary jar you mention.

I bet you are not the only one to propose a test support class for a grails plugin. I wonder how it is done in those?
