### ISSUE TITLE
MockHttpServletRequest Exception on Production mode only

### ISSUE THREAD

**Issue by uris77** [robfletcher/grails-gson#38]
I'm getting this exception on production mode only:

```
org.springframework.mock.web.MockHttpServletRequest. Stacktrace follows:
java.lang.ClassNotFoundException: org.springframework.mock.web.MockHttpServletRequest
```

It works fine on development mode.

**Comment by uris77** [comment]
BTW, this is the rest of the stack trace:

```
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
    at java.lang.Class.getDeclaredMethods(Class.java:1810)
    at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
    at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
    at grails.plugin.gson.converters.GSON.render(GSON.groovy:57)
    at grails.plugin.gson.api.ArtefactEnhancer$_enhanceControllers_closure1.doCall(ArtefactEnhancer.groovy:29)
    at introcloud.AttendeeMeetingRequestController$_renderList_closure4_closure5.doCall(AttendeeMeetingRequestController.groovy:39)
    at introcloud.AttendeeMeetingRequestController.renderList(AttendeeMeetingRequestController.groovy:36)
    at introcloud.AttendeeMeetingRequestController.list(AttendeeMeetingRequestController.groovy:16)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)

```

This only happens when I use 

``` groovy

render aList as GSON

```

**Comment by robfletcher** [comment]
I'm trying to replicate this issue with the test application. For instance the AlbumController class uses the render method. I run the app up using `grails prod run-app` then hit `curl http://localhost:8080/albums` which does `render Album.list(params) as GSON` in the controller. Everything's working for me. Is there something else that could be missing here?

**Comment by uris77** [comment]
Try it with 

```
grails prod run-war
```

It is what we used to replicate it in our dev environment.

**Comment by robfletcher** [comment]
When I try that I get a StackOverflowError!

**Comment by felipebremer** [comment]
I had this problem too.
I solved this problem, adding in my dependencies this plugin:
runtime ("org.springframework:spring-test:2.5")
After add this and generate the war, all is ok.

**Comment by ppazos** [comment]
Solution worked for me.
